# PyTorch

## Tensor
- multi-dimensional array

### install required libraries

In [ ]:
%pip install torch torchvision torchaudio torchtext

### import required libraries

In [4]:
import torch

In [14]:
torch.__version__

'2.6.0'

In [27]:
# cuda will be available for NVidia GPUs
torch.cuda.is_available()

False

In [31]:
# mps will be available on apple machines (M1, M2, M3 and M4)
torch.mps.is_available()

True

### create tensors using torch.tensor()

In [23]:
# scalar tensor
t1 = torch.tensor(10)

print(f"t1 = {t1}")
print(f"type of t1 = {type(t1)}")
print(f"value inside t1 = {t1.item()}")
print(f"shape of t1 = {t1.shape}")
print(f"type of item stored in t1 = {t1.dtype}")
print(f"size of t1 = {t1.size()}")
print(f"t1 is loaded on {t1.device} device")

t1 = 10
type of t1 = <class 'torch.Tensor'>
value inside t1 = 10
shape of t1 = torch.Size([])
type of item stored in t1 = torch.int64
size of t1 = torch.Size([])
t1 is loaded on cpu device


In [33]:
# if you are running the code on non-apple machine, replace mps with cuda
#  t1.to("cuda")
t1_gpu = t1.to("mps")
print(f"t1_gpu is loaded on {t1_gpu.device} device")

t1_gpu is loaded on mps:0 device


In [24]:
# Vector (1D tensor)
t2 = torch.tensor([10, 20, 30, 40, 50])

print(f"t2 = {t2}")
print(f"type of t2 = {type(t2)}")
print(f"shape of t2 = {t2.shape}")
print(f"type of item stored in t2 = {t2.dtype}")
print(f"size of t2 = {t2.size()}")
print(f"t2 is loaded on {t2.device} device")

# item() is available only for scalar tensor
# print(f"value inside t2 = {t2.item()}")

t2 = tensor([10, 20, 30, 40, 50])
type of t2 = <class 'torch.Tensor'>
shape of t2 = torch.Size([5])
type of item stored in t2 = torch.int64
size of t2 = torch.Size([5])
t2 is loaded on cpu device


In [25]:
# Matrix (2D tensor) of size 3x2
t3 = torch.tensor([[10, 20], [30, 40], [50, 60]])

print(f"t3 = {t3}")
print(f"type of t3 = {type(t3)}")
print(f"shape of t3 = {t3.shape}")
print(f"type of item stored in t3 = {t3.dtype}")
print(f"size of t3 = {t3.size()}")
print(f"t3 is loaded on {t3.device} device")

t3 = tensor([[10, 20],
        [30, 40],
        [50, 60]])
type of t3 = <class 'torch.Tensor'>
shape of t3 = torch.Size([3, 2])
type of item stored in t3 = torch.int64
size of t3 = torch.Size([3, 2])
t3 is loaded on cpu device


In [51]:
# create a tensor 
t = torch.tensor([10, 20, 30, 40])
print(f"type of t = {t.dtype}")
print(f"size of t = {t.size()}")
print(f"no of byes required to store the tensor = {t.nbytes} bytes")


type of t = torch.int64
size of t = torch.Size([4])
no of byes required to store the tensor = 32 bytes


In [53]:
# create a tensor 
t = torch.tensor([10, 20, 30, 40], dtype=torch.int32)

print(f"type of t = {t.dtype}")
print(f"size of t = {t.size()}")
print(f"no of byes required to store the tensor = {t.nbytes} bytes")

type of t = torch.int32
size of t = torch.Size([4])
no of byes required to store the tensor = 16 bytes


In [55]:
# create a tensor 
t = torch.tensor([10, 20, 30, 40], dtype=torch.int16)
print(f"type of t = {t.dtype}")
print(f"size of t = {t.size()}")
print(f"no of byes required to store the tensor = {t.nbytes} bytes")

type of t = torch.int16
size of t = torch.Size([4])
no of byes required to store the tensor = 8 bytes


In [59]:
# create a tensor 
t = torch.tensor([10, 20, 30, 40], dtype=torch.int8)
print(f"t = {t}")
print(f"type of t = {t.dtype}")
print(f"size of t = {t.size()}")
print(f"no of byes required to store the tensor = {t.nbytes} bytes")

t = tensor([10, 20, 30, 40], dtype=torch.int8)
type of t = torch.int8
size of t = torch.Size([4])
no of byes required to store the tensor = 4 bytes


In [58]:
# create a tensor 
t = torch.tensor([10, 20, 30, 40], dtype=torch.float16)
print(f"t = {t}")
print(f"type of t = {t.dtype}")
print(f"size of t = {t.size()}")
print(f"no of byes required to store the tensor = {t.nbytes} bytes")

t = tensor([10., 20., 30., 40.], dtype=torch.float16)
type of t = torch.float16
size of t = torch.Size([4])
no of byes required to store the tensor = 8 bytes


### create tensor using utility functions

In [34]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [39]:
# create a scalar tensor
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

In [38]:
# create a matrix tensor
torch.ones(4, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [40]:
# create a matrix tensor
torch.zeros(4, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [44]:
# create a tensor with random values
print(torch.rand(5))
print(torch.rand(5, 5))

tensor([0.3497, 0.4806, 0.9791, 0.2289, 0.5849])
tensor([[0.1149, 0.2969, 0.1553, 0.2686, 0.0079],
        [0.1223, 0.8867, 0.7770, 0.8116, 0.4471],
        [0.3197, 0.3417, 0.7633, 0.5209, 0.9645],
        [0.4632, 0.5628, 0.3210, 0.7970, 0.0618],
        [0.1615, 0.8004, 0.2612, 0.6652, 0.1266]])


In [46]:
# create a tensor using normal distribution
print(torch.randn(5))
print(torch.randn(5, 4))

tensor([-0.1942, -0.1389, -0.3344, -0.2456, -0.2533])
tensor([[ 1.0309,  0.4392, -0.1762, -0.9288],
        [ 0.3464, -0.1895, -0.4222, -1.1735],
        [-1.1390, -0.2932, -0.9929,  0.1354],
        [ 0.9396, -2.5688, -0.5845,  0.7574],
        [ 0.0359, -2.1070,  1.5142,  1.1835]])
